---
clickhouse:
  hosts: 
    clickhouse-server:
      ansible_host: 84.201.179.216
vector:
  hosts:
    vector-server: 
      ansible_host: 51.250.106.26
lighthouse:
  hosts:
    lighthouse-server: 
      ansible_host: 51.250.102.176